#!/usr/bin/env bash
set -euo pipefail

scheme_file="${XDG_STATE_HOME:-$HOME/.local/state}/caelestia/scheme.json"
firefox_profile_dir="${HOME}/.config/mozilla/firefox/dx8dmq8x.default-release"
chrome_dir="${firefox_profile_dir}/chrome"
colors_file="${chrome_dir}/caelestia-colors.css"

if [[ ! -f "$scheme_file" ]]; then
  exit 0
fi

mkdir -p "$chrome_dir"

export SCHEME_FILE="$scheme_file"
export COLORS_FILE="$colors_file"

python - <<'PY'
import json, os
from pathlib import Path

scheme_file = os.environ["SCHEME_FILE"]
with open(scheme_file, "r", encoding="utf-8") as f:
    data = json.load(f)

cols = data.get("colours", {})

def c(key):
    return cols.get(key, "")

def hex_alpha(key, alpha_pct):
    val = c(key)
    if not val:
        return None
    a = round(alpha_pct / 100 * 255)
    return f"#{val}{a:02x}"

bg = c("background")
on_bg = c("onBackground")
primary = c("primary")
on_primary = c("onPrimary")
surface_container = c("surfaceContainer")
surface_container_high = c("surfaceContainerHigh")
surface_variant = c("surfaceVariant")
outline = c("outline")
outline_variant = c("outlineVariant")

if not bg:
    exit(0)

# Transparencias para Glassmorphism
window_bg_alpha = hex_alpha("background", 60)         # Fondo general de la ventana
titlebar_bg_alpha = hex_alpha("surfaceContainer", 75) # Barra de pestañas (titlebar)
toolbar_bg_alpha = hex_alpha("surfaceContainer", 70)  # Barra de herramientas superior
urlbar_bg_alpha = hex_alpha("surfaceContainerHigh", 80) # Barra de URL
tab_active_bg = hex_alpha("primary", 80)              # Pestaña activa
tab_hover_bg = hex_alpha("surfaceVariant", 50)        # Pestaña al pasar el mouse
menu_bg = hex_alpha("surfaceContainer", 90)           # Menús desplegables
newtab_bg_alpha = hex_alpha("surfaceContainer", 65)       # Fondo nueva pestaña
newtab_shortcut_alpha = hex_alpha("surfaceContainerHigh", 70) # Accesos directos
newtab_shortcut_hover_alpha = hex_alpha("surfaceContainerHigh", 85)

css_content = f"""/* Auto-generated by Caelestia hook */
:root {{
    /* Window and general backgrounds */
    --lwt-accent-color: {window_bg_alpha} !important;
    --titlebar-bgcolor: {titlebar_bg_alpha} !important;
    --toolbar-bgcolor: {toolbar_bg_alpha} !important;
    --lwt-text-color: #{on_bg} !important;
    --toolbar-color: #{on_bg} !important;
    
    /* URL bar fields */
    --toolbar-field-background-color: {urlbar_bg_alpha} !important;
    --toolbar-field-color: #{on_bg} !important;
    --toolbar-field-border-color: #{outline_variant} !important;
    --toolbar-field-focus-background-color: #{surface_container} !important;
    --toolbar-field-focus-border-color: #{primary} !important;
    --toolbar-field-focus-color: #{on_bg} !important;
    
    /* Tabs */
    --lwt-selected-tab-background-color: {tab_active_bg} !important;
    --tab-selected-bgcolor: {tab_active_bg} !important;
    --tab-selected-textcolor: #{on_primary} !important;
    --lwt-tab-text: #{on_bg} !important;
    --tab-hover-bgcolor: {tab_hover_bg} !important;
    --tab-line-color: transparent !important;
    
    /* Popups and Menus */
    --arrowpanel-background: {menu_bg} !important;
    --arrowpanel-color: #{on_bg} !important;
    --arrowpanel-border-color: #{outline} !important;
    
    /* Sidebar */
    --lwt-sidebar-background-color: {window_bg_alpha} !important;
    --lwt-sidebar-text-color: #{on_bg} !important;
    
    /* New Tab page */
    --newtab-bgcolor: {newtab_bg_alpha} !important;
    --newtab-shortcut-bgcolor: {newtab_shortcut_alpha} !important;
    --newtab-shortcut-hover-bgcolor: {newtab_shortcut_hover_alpha} !important;
}}
"""

out_path = os.environ.get("COLORS_FILE", "")
Path(out_path).write_text(css_content)
PY
