#!/usr/bin/env bash
set -euo pipefail

scheme_file="${XDG_STATE_HOME:-$HOME/.local/state}/caelestia/scheme.json"
kitty_conf_dir="${XDG_CONFIG_HOME:-$HOME/.config}/kitty"
kitty_theme_file="$kitty_conf_dir/caelestia.conf"

if [[ ! -f "$scheme_file" ]]; then
  exit 0
fi

mkdir -p "$kitty_conf_dir"

get_color() {
  local key="$1"
  python - "$key" <<'PY'
import json, sys, os
key = sys.argv[1]
path = os.environ.get("SCHEME_FILE")
with open(path, "r", encoding="utf-8") as f:
    data = json.load(f)
val = data.get("colours", {}).get(key, "")
if val:
    print(val)
PY
}

export SCHEME_FILE="$scheme_file"

background=$(get_color background)
foreground=$(get_color onBackground)
primary=$(get_color primary)
on_primary=$(get_color onPrimary)
outline_variant=$(get_color outlineVariant)
secondary=$(get_color secondary)
term0=$(get_color term0)
term1=$(get_color term1)
term2=$(get_color term2)
term3=$(get_color term3)
term4=$(get_color term4)
term5=$(get_color term5)
term6=$(get_color term6)
term7=$(get_color term7)
term8=$(get_color term8)
term9=$(get_color term9)
term10=$(get_color term10)
term11=$(get_color term11)
term12=$(get_color term12)
term13=$(get_color term13)
term14=$(get_color term14)
term15=$(get_color term15)

if [[ -z "$background" || -z "$foreground" || -z "$term0" || -z "$term15" ]]; then
  exit 0
fi

cat > "$kitty_theme_file" <<EOF
# Auto-generated by Caelestia hook
# Do not edit manually

# Base colors
foreground #$foreground
background #$background

# Cursor and selection
cursor #$secondary
cursor_text_color #$background
selection_background #$primary
selection_foreground #$on_primary

# URL and borders
url_color #$primary
active_border_color #$primary
inactive_border_color #$outline_variant
bell_border_color #$secondary

# Tab bar
active_tab_foreground #$on_primary
active_tab_background #$primary
inactive_tab_foreground #$foreground
inactive_tab_background #$background
tab_bar_background #$background

# Scrollbar
scrollbar_handle_color #$term8
scrollbar_track_color #$background

# 16-color palette (from Caelestia scheme)
color0  #$term0
color1  #$term1
color2  #$term2
color3  #$term3
color4  #$term4
color5  #$term5
color6  #$term6
color7  #$term7
color8  #$term8
color9  #$term9
color10 #$term10
color11 #$term11
color12 #$term12
color13 #$term13
color14 #$term14
color15 #$term15
EOF

if command -v kitty >/dev/null 2>&1; then
  kitty @ set-colors --all "$kitty_theme_file" >/dev/null 2>&1 || true
  if [[ -S /tmp/kitty ]]; then
    KITTY_LISTEN_ON=unix:/tmp/kitty kitty @ set-colors --all "$kitty_theme_file" >/dev/null 2>&1 || true
  fi
fi
