$background = 131314
$onBackground = e4e2e2
$surface = 131314
$surfaceDim = 131314
$surfaceBright = 39393a
$surfaceContainerLowest = 0e0e0f
$surfaceContainerLow = 1b1c1c
$surfaceContainer = 1f2020
$surfaceContainerHigh = 2a2a2a
$surfaceContainerHighest = 353535
$onSurface = e4e2e2
$surfaceVariant = 43474a
$onSurfaceVariant = c3c7ca
$outline = 8d9195
$outlineVariant = 43474a
$inverseSurface = e4e2e2
$inverseOnSurface = 303031
$shadow = 000000
$scrim = 000000
$surfaceTint = bbc8d2
$primary = bbc8d2
$primaryDim = e5f3fd
$onPrimary = 26323a
$primaryContainer = 85939c
$onPrimaryContainer = 0b171e
$inversePrimary = 536069
$primaryFixed = d7e4ee
$primaryFixedDim = bbc8d2
$onPrimaryFixed = 111d24
$onPrimaryFixedVariant = 3c4851
$secondary = c3c7cb
$secondaryDim = dfe3e7
$onSecondary = 2c3134
$secondaryContainer = 454a4d
$onSecondaryContainer = b5b9bd
$secondaryFixed = dfe3e7
$secondaryFixedDim = c3c7cb
$onSecondaryFixed = 171c1f
$onSecondaryFixedVariant = 43474b
$tertiary = d1c2d2
$tertiaryDim = f4e3f4
$onTertiary = 372d3a
$tertiaryContainer = 9a8c9c
$onTertiaryContainer = 1b131e
$tertiaryFixed = eeddef
$tertiaryFixedDim = d1c2d2
$onTertiaryFixed = 211824
$onTertiaryFixedVariant = 4e4351
$error = ffb4ab
$errorDim = ff554a
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryPaletteKeyColor = 6c7982
$secondaryPaletteKeyColor = 73787c
$tertiaryPaletteKeyColor = 887b8a
$neutralPaletteKeyColor = 787777
$neutralVariantPaletteKeyColor = 73777b
$errorPaletteKeyColor = de3730
$primary_paletteKeyColor = 6c7982
$secondary_paletteKeyColor = 73787c
$tertiary_paletteKeyColor = 887b8a
$neutral_paletteKeyColor = 787777
$neutral_variant_paletteKeyColor = 73777b
$term0 = 343434
$term1 = 8383ff
$term2 = 43def3
$term3 = 75fcdd
$term4 = 7db2ca
$term5 = 80adeb
$term6 = 85d5eb
$term7 = ccdcd6
$term8 = 9aa59f
$term9 = a29eff
$term10 = 7fedff
$term11 = c9fff3
$term12 = a6c6d2
$term13 = a2c0f7
$term14 = 8de8ff
$term15 = ffffff
$rosewater = f4f0fa
$flamingo = dfe0f5
$pink = c8dfff
$mauve = 8ac5ff
$red = 8ab5ff
$maroon = abbef0
$peach = e0c2f9
$yellow = d0f9f4
$green = a2ebff
$teal = b0e8ff
$sky = abe3ff
$sapphire = 83d1fa
$blue = 76c5f9
$lavender = 9cd3ff
$klink = 2890c1
$klinkSelection = 2e8fc3
$kvisited = 1885d5
$kvisitedSelection = 2684d6
$knegative = 607eff
$knegativeSelection = 607eff
$kneutral = c794ff
$kneutralSelection = c794ff
$kpositive = 00b9db
$kpositiveSelection = 00b8de
$text = e4e2e2
$subtext1 = c3c7ca
$subtext0 = 8d9195
$overlay2 = 7b7e82
$overlay1 = 686b6e
$overlay0 = 57595c
$surface2 = 47484a
$surface1 = 363739
$surface0 = 252526
$base = 131314
$mantle = 131314
$crust = 121213
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
