$background = 131315
$onBackground = e5e1e4
$surface = 131315
$surfaceDim = 131315
$surfaceBright = 3a393b
$surfaceContainerLowest = 0e0e10
$surfaceContainerLow = 1c1b1d
$surfaceContainer = 201f21
$surfaceContainerHigh = 2a2a2c
$surfaceContainerHighest = 353436
$onSurface = e5e1e4
$surfaceVariant = 47464d
$onSurfaceVariant = c8c5ce
$outline = 919098
$outlineVariant = 47464d
$inverseSurface = e5e1e4
$inverseOnSurface = 313032
$shadow = 000000
$scrim = 000000
$surfaceTint = c3c4e4
$primary = c3c4e4
$primaryDim = ddddfe
$onPrimary = 2c2e47
$primaryContainer = 9394b2
$onPrimaryContainer = 2b2d46
$inversePrimary = 5b5c78
$primaryFixed = e0e0ff
$primaryFixedDim = c3c4e4
$onPrimaryFixed = 171931
$onPrimaryFixedVariant = 43455f
$secondary = c7c5d3
$secondaryDim = e3e1ef
$onSecondary = 2f2f3a
$secondaryContainer = 484854
$onSecondaryContainer = b8b7c5
$secondaryFixed = e3e1ef
$secondaryFixedDim = c7c5d3
$onSecondaryFixed = 1a1b25
$onSecondaryFixedVariant = 464651
$tertiary = e0bcd5
$tertiaryDim = fbd5ee
$onTertiary = 41283b
$tertiaryContainer = ae8da4
$onTertiaryContainer = 40273a
$tertiaryFixed = fed8f1
$tertiaryFixedDim = e0bcd5
$onTertiaryFixed = 2a1426
$onTertiaryFixedVariant = 593e52
$error = ffb4ab
$errorDim = ff554a
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryPaletteKeyColor = 747592
$secondaryPaletteKeyColor = 767682
$tertiaryPaletteKeyColor = ae8da4
$neutralPaletteKeyColor = 787678
$neutralVariantPaletteKeyColor = 77767e
$errorPaletteKeyColor = de3730
$primary_paletteKeyColor = 747592
$secondary_paletteKeyColor = 767682
$tertiary_paletteKeyColor = ae8da4
$neutral_paletteKeyColor = 787678
$neutral_variant_paletteKeyColor = 77767e
$term0 = 353434
$term1 = a775ff
$term2 = 44def5
$term3 = ffdcf2
$term4 = 97aad7
$term5 = b19feb
$term6 = 9dceff
$term7 = e8d3de
$term8 = ac9fa9
$term9 = bc95ff
$term10 = 89ecff
$term11 = fff0f6
$term12 = b4c1dc
$term13 = c7b5f5
$term14 = bae0ff
$term15 = ffffff
$rosewater = f7eff9
$flamingo = e8def3
$pink = e0d8ff
$mauve = bcb9ff
$red = bea6fe
$maroon = c7b6ee
$peach = e0c2f9
$yellow = ffecf3
$green = c8e3ff
$teal = d2e0ff
$sky = cedaff
$sapphire = b5c5ff
$blue = aeb8ff
$lavender = c5c9ff
$klink = 6e83d1
$klinkSelection = 6e83d1
$kvisited = 7b74db
$kvisitedSelection = 7c73db
$knegative = 996bff
$knegativeSelection = 9a6bff
$kneutral = c794ff
$kneutralSelection = c794ff
$kpositive = 60adff
$kpositiveSelection = 60adff
$text = e5e1e4
$subtext1 = c8c5ce
$subtext0 = 919098
$overlay2 = 7e7d84
$overlay1 = 6b6a70
$overlay0 = 59595e
$surface2 = 48484c
$surface1 = 37373a
$surface0 = 252527
$base = 131315
$mantle = 131315
$crust = 121214
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
