xwayland {
  force_zero_scaling = true
}

# Monitor Secundario (MSI Optix G24C) - Izquierda
monitor=HDMI-A-1,1920x1080@119.99,0x0,1

# Monitor Principal (Samsung LC27G5xT) - Derecha
monitor=DP-2,2560x1440@143.99,1920x0,1.25

# TV (LG) - A la izquierda del monitor izquierdo (más allá de HDMI‑A‑1)
monitor=HDMI-A-2,1920x1080@60,-1920x0,1
