
#######################
###### MAIN FILE ######
#######################

source = ~/.config/hypr/env.conf
source = ~/.config/hypr/variables.conf
source = ~/.config/hypr/permissions.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/general.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/windowrules.conf
source = ~/.cache/caelestia/themes/hypr.conf

# Workspaces para Monitor Secundario (HDMI-A-1, izquierda): 5 dedicados
workspace = 6, monitor:HDMI-A-1, default:true
workspace = 7, monitor:HDMI-A-1
workspace = 8, monitor:HDMI-A-1
workspace = 9, monitor:HDMI-A-1
workspace = 10, monitor:HDMI-A-1
# Workspaces para Monitor Principal (DP-2, derecha): 5 dedicados
workspace = 1, monitor:DP-2, default:true
workspace = 2, monitor:DP-2
workspace = 3, monitor:DP-2
workspace = 4, monitor:DP-2
workspace = 5, monitor:DP-2 

# Workspace para TV (HDMI-A-2): 1 dedicado
workspace = 11, monitor:HDMI-A-2, default:true
