wallpaper {
  monitor = DP-2
  path = ~/Wallpapers/xZepyx wallpapers/
  timeout = 900
}

wallpaper {
  monitor = HDMI-A-1
  path = ~/Wallpapers/xZepyx wallpapers/
  timeout = 900
}

wallpaper {
  monitor = HDMI-A-2
  path = ~/Wallpapers/xZepyx wallpapers/
  timeout = 900
}
