###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use

$terminal = kitty
$terminalAlt = warp-terminal
$fileManager = $terminal -e yazi
$menu = caelestia:launcher
$mainMod = SUPER # Sets "Windows" key as main modifier
$browser = firefox
$scriptsDir = ~/.config/hypr/scripts
